package licenses

import _ "embed"

// notices is generated by `make licenses` from the production Go and Rust
// dependency graphs plus independently embedded runtime assets.
//
//go:embed THIRD_PARTY_NOTICES.txt
var notices string

// Text returns the complete third-party attribution bundled into ALT.
func Text() string {
	return notices
}
